'''Common module contains constants and helpers for the main Anal program'''

# Basic program usage string
USAGE = 'Usage: anal <resource>'

# Longer help text for -h option or in response to bad input
FULL_HELP = 'Anal\n\nUsage: anal <host>]\n\nUsed to perform text analysis on a file or web resource.\n\n<resource> may be either a path to a local file or a web URL.\nURLs should include \'http(s)://\''

FREQ_RESULTS = 15

# Characters to replace with empty string
EXCLUDE = set(['.',
    ';',
    ',',
    '!',
    '?',
    '(',
    ')',
    '[',
    ']',
    '{',
    '}',
    '*',
    u'\u2026',
    u'\u2013',
    u'\u2014',
    '"',
    u'\u201C',
    u'\u201D',
    '|'
    ])

# Words/strings that don't contribute meaning to a piece
COMMON_WORDS = [
    '',
    '\n',
    '\r\n',
    'a',
    'the',
    'an',
    'and',
    'they',
    'they\'ll',
    'it',
    'it\'ll',
    'us',
    'you',
    'my',
    'out',
    'don\'t',
    'i',
    'from',
    'in',
    'as',
    'where',
    'when',
    'who',
    'because',
    'why',
    'how',
    'since',
    'is',
    'it\'s',
    'its',
    'she',
    'he',
    'he\'ll',
    'she\'ll',
    'all',
    'every',
    'each',
    'thing',
    'if',
    'to',
    'we',
    'of',
    'are',
    'be',
    'not',
    'for',
    'that',
    'our',
    'or',
    'by',
    ' ',
    '  ',
    'her',
    'was',
    'this',
    'his',
    'with',
    'then',
    'do',
    'has',
    'on',
    'what',
    'should',
    'have',
    'after',
    'been',
    'would',
    'were',
    'but',
    'their',
    'more',
    'can',
    'than',
    'most',
    'them',
    'your',
    'only',
    'so',
    'many',
    'much',
    'even',
    'at',
    'those',
    'had',
    'says'
    ]
